# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
n=np.random.random((3,3,3))
print(n)

[[[0.52575014 0.230055   0.83859284]
  [0.92170085 0.40455389 0.66894271]
  [0.44175663 0.2885159  0.15712619]]

 [[0.65628047 0.74762502 0.86087146]
  [0.07589887 0.98298942 0.25423869]
  [0.62428437 0.93382855 0.51486693]]

 [[0.01662296 0.3228208  0.08360676]
  [0.53945946 0.90097111 0.50774685]
  [0.40396664 0.29645058 0.41689906]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
x=np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
x=np.ones((3,3))
print("Checkboard pattern:")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

Checkboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
x=np.random.random((3,3))
print("Original Array:")
print(x)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("After normalization:")
print(x)

Original Array:
[[0.1089248  0.18213742 0.93935924]
 [0.74628652 0.20751099 0.09148305]
 [0.67985866 0.3267803  0.31438253]]
After normalization:
[[0.0205711  0.10691936 1.        ]
 [0.77228666 0.13684539 0.        ]
 [0.69394048 0.2775137  0.26289154]]


# 5.  How to find common values between two arrays?

In [5]:

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [7]:

x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[1 0 1 1 1 0]
Second array:
[0 1 1 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:

x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)


Original array:
[0.55971895 0.19885707 0.98699182 0.50925306 0.74200086 0.461177
 0.4390705  0.35051056 0.24853721 0.88808438]
Maximum value replaced by -1:
[ 0.55971895  0.19885707 -1.          0.50925306  0.74200086  0.461177
  0.4390705   0.35051056  0.24853721  0.88808438]


# 9. How to print all the values of an array?

In [13]:

import numpy as np
n=np.array([1,2,3,4,5])
print("Values of an array:",n)

Values of an array: [1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [10]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.61120292 0.90866518 0.77148062 0.59712384 0.55335008 0.79006592
  0.61163531 0.88283406 0.03776466 0.45912524]
 [0.8180768  0.22557149 0.23424554 0.5710008  0.34655175 0.81923763
  0.55582491 0.25649563 0.76077862 0.7680318 ]
 [0.2894431  0.21099989 0.22856361 0.8478128  0.07367413 0.22206166
  0.6538109  0.33335934 0.53931583 0.66851937]
 [0.34534421 0.48965828 0.42386108 0.00100764 0.21552747 0.55577941
  0.99475869 0.88219349 0.96600931 0.07990296]
 [0.61804007 0.1713967  0.03464062 0.67561649 0.96379401 0.64119352
  0.7534388  0.84427578 0.25661889 0.35590029]]

Subtract the mean of each row of the said matrix:

[[-0.01112186  0.28634039  0.14915584 -0.02520094 -0.0689747   0.16774114
  -0.01068947  0.26050927 -0.58456012 -0.16319955]
 [ 0.2824953  -0.31001001 -0.30133596  0.03541931 -0.18902975  0.28365613
   0.02024342 -0.27908587  0.22519712  0.23245031]
 [-0.11731296 -0.19575617 -0.17819245  0.44105673 -0.33308193 -0.18469441
   0.24705484 -0.07339672  0.1

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(4, 3)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 12.How to get the diagonal of a dot product?

In [14]:
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

# 13.How to find the most frequent value in an array?

In [15]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[9 7 3 5 8 5 2 2 4 0 7 4 8 0 6 5 3 0 7 7 9 3 4 9 4 8 1 3 0 3 1 7 2 2 8 8 9
 8 6 8]
Most frequent value in the above array:
8


# 14.How to get the n largest values of an array

In [16]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [17]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
